version: 2

project_name: wtui

before:
  hooks:
    - go run github.com/tc-hib/go-winres@v0.3.3 make --in cmd/wtui/winres/winres.json --out cmd/wtui/rsrc --arch amd64,arm64 --product-version git-tag --file-version git-tag

builds:
  - id: wtui
    main: ./cmd/wtui
    binary: wtui
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -X main.Version={{ .Tag }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: wtui
    ids:
      - wtui
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "wtui_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md

checksum:
  name_template: checksums.txt
